### ISSUE TITLE
Space Traveler's Hub Kanban Board Setup

### ISSUE THREAD

**Issue by Lameck1** [mugberto/space-travelers-hub#25]
# Description
Link to project: [Space Travelers' Hub - Kanban Board](https://github.com/mugberto/space-travelers-hub/projects/1)

NOTE: Right-click the above ☝🏼  link and open it in a new tab or click on it but refresh the page thereafter, somehow it doesn't load the project immediately when clicked.

The contributors to this project are two, namely:
- [Hubert MUGABO](https://github.com/mugberto)
- [Lameck Otieno](https://github.com/Lameck1)

**Comment by dasileker** [comment]
### **Hi @Lameck1 @mugberto** 

### **Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
